### ISSUE TITLE
curse project unable to find candidate

### ISSUE THREAD

**Issue by thisischrys** [MCUpdater/MCU-API#11]
project matches the last part of the url which I think is right?

( https://minecraft.curseforge.com/projects/mo-bends )
`<Curse project="mo-bends" type="RELEASE" autoupgrade="true"/>`
Unable to find candidate for curse:mo-bends after checking 18 files 
Unable to fetch MD5 for curse:mo-bends with no URL 

( https://minecraft.curseforge.com/projects/betterfps )
`<Curse project="betterfps" type="RELEASE" autoupgrade="true"/>`
Unable to find candidate for curse:betterfps after checking 22 files 
Unable to fetch MD5 for curse:betterfps with no URL

**Comment by allaryin** [comment]
Can you share the whole pack xml? It looks like you've got MC version mismatches or similar. For example, in the MC1.12 section of the optionals pack, I specify:

```xml
<Module name="BetterFPS [beta]" id="betterfps" depends="" side="CLIENT">
	<Curse project="betterfps" file="2483393"/>
	<Required isDefault="true">false</Required>
	<ModType>Regular</ModType>
	<MD5>d36f4d3c0f96e99a9a1ad2e8eeda1fc4</MD5>
	<Meta>
		<description>BetterFps is a Minecraft mod that add a few performance improvements, trying to be compatible with other mods.</description>
		<version>1.4.8</version>
		<authors>Guichaguri</authors>
	</Meta>
</Module>
```

But the discovery portion should still work with the file id and md5 removed.

**Comment by thisischrys** [comment]
https://pastebin.com/qvSuxGEN

**Comment by allaryin** [comment]
This file doesn't include the syntax you tried with those two mods ;)

But I think I see your problem. You're likely requesting a release build. There isn't a release build of BetterFPS or Mo'Bends for MC1.12.

**Comment by thisischrys** [comment]
Oops, I just undid it and saved it literally right before I copy pasted it here.
Tried it with beta, that was indeed the problem

**Comment by allaryin** [comment]
I will update the messaging in this situation to make the solution more obvious.
