### ISSUE TITLE
gson-2.2.4.jar has the wrong checksum in http://files.mcupdater.com/Bootstrap.xml

### ISSUE THREAD

**Issue by endumiuz** [MCUpdater/MCU-API#16]
(I'm not sure in which issue tracker this should be reported.)

I verified that I didn't have a corrupt gson-2.2.4.jar by downloading it a couple of times and it always has the same md5 checksum, but in the xml-file it's different.

**Comment by smbarbour** [comment]
Corrected.  I'm honestly not sure how this happened...  as far as I can tell, this is the version we've been using, but the filesize and MD5 were incorrect.
