### ISSUE TITLE
Delete old files when ModPath changes

### ISSUE THREAD

**Issue by Baughn** [MCUpdater/MCU-API#3]
For a Module entry such as
``    <Module id="TiCTooltips" name="TiCTooltips">``
``      <URL>http://example.com/mods/TiCTooltips-mc1.6.4-1.1.5.jar</URL>``
``      <Required>True</Required>``
``      <MD5>3b3cc2530106091aa1eb245e5059c536</MD5>``
``      <ModType>Regular</ModType>``
``      <ModPath>mods/TiCTooltips-mc1.6.4-1.1.5.jar</ModPath>``
``    </Module>``

When the ModPath changes, MCUpdater will create a new .jar without deleting the old one. It should delete the old one.

**Comment by smbarbour** [comment]
Implemented in b8cea7ad0669ed61e7eeeeaaa4142890d59053f9
