### ISSUE TITLE
Use a non-instance directory for tmpFolder

### ISSUE THREAD

**Issue by Baughn** [MCUpdater/MCU-API#4]
At MCUpdate.java:291, you create a temp folder inside the instance directory. This often fails on my installation, because I have some mod that creates a file called 'temp'; I haven't tried very hard to figure out which one. Somehow the result of that becomes a NullPointerException during launch. Does "0.jar" ring any bells?

The most obvious fix would be to create it at the top-level .MCUpdater directory, or you could use a random name instead.

**Comment by smbarbour** [comment]
Fixed by 135f33022321cfe25da348b44149d8c67af859b6
